### PR TITLE
Documentation system

### PR DESCRIPTION
**Pull request by julian-gehring**
Who doesn't love to write documentation?

The idea here is to set up a framework for documenting the package. Once the framework is good enough, we can merge it into master and do something useful with it, i.e. actually start documenting.

At the moment, this features:
- Generate API manual in markdown from julia docstrings with `Lexicon`
- Convert notebooks to markdown and display them in the documentation
- Build the documentation with mkdocs and readthedocs (http://multipletestingjl.readthedocs.org/en/docs/).

### CODE REVIEW

**Comment by nignatiadis** [comment]
That's quite cool :+1: ! Which other packages use a similar documentation system?

**Comment by julian-gehring** [comment]
Rendering of the docstrings with Lexicon is used by some packages which are listed in the Lexicon.jl repo. Some use it with readthedocs, others host the documentation on github (e.g. Sims.jl).

The automatic conversion of the notebooks I have figured out myself - but it's also not really rocket sciene ;)

**Comment by julian-gehring** [comment]
The rendering of the API with Lexicon/mkdocs still needs fine-tuning though.

**Comment by julian-gehring** [comment]
Do you think this is good enough to go? From my perspective, the documentation framework fulfils its role. We will have to figure out a good structure of the docstrings, but this is probably easiest do see along the way.

**Comment by nignatiadis** [comment]
Yeah looks good! I don't think there's any reason against going ahead and merging it now.

**Pull request merged**
